version: '3'

services:
  trip:
    build: .
    container_name: trip
    ports:
      - 8090:8090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 1s
      timeout: 1s
      retries: 5
  client:
    build: 
      context: .
      dockerfile: DockerfileClient
    restart: on-failure
    depends_on:
      - trip
    environment:
      - HOST_API=http://trip:8090
    links: 
      - trip
